name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # GCP Auth
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Web Server deploy
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          source: src
          service: speaking-hands-api
          project_id: ${{ env.GCP_PROJECT_ID }}
          region: europe-west3
          timeout: 20m
          flags: "--allow-unauthenticated --platform=managed"